### ISSUE TITLE
Does this library works for Vizio Internet Apps Plus?

### ISSUE THREAD

**Issue by ozvi** [JohnWickham/homebridge-vizio#6]
There are alot of  Vizio SmartCast repos out there.

But does anybody knows if this library works on Vizio's Internet Apps Plus? Is it newer?

**Comment by JohnWickham** [comment]
This plugin is only for adding your Vizio display as a HomeKit accessory to turn the display on or off. It should work with any Smartcast display, but doesn’t have any special integration with Vizio’s apps.

**Comment by osfunapps** [comment]
Vizio Internet Apps Plus it's another way for Vizio smart tv to communicate with other devices. It's another os made/adopted by Vizio.

**Comment by JohnWickham** [comment]
Thanks for that clarification, @osfunapps! I'm not familiar yet with Internet Apps Plus, so if it uses a different API than other Vizio displays, homebridge-vizio may not be compatible. I haven’t tested this as I don’t have a display that uses Internet Apps Plus. Perhaps someone who does could test?
